apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: pylon
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: pylon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http