apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: pylon
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: pylon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification-service
  ports:
    - port: 9004
      targetPort: http
      protocol: TCP
      name: http