apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/kodokbakar/pylon/api-gateway
    newName: pylon/api-gateway
    newTag: latest
  - name: ghcr.io/kodokbakar/pylon/chat-service
    newName: pylon/chat-service
    newTag: latest
  - name: ghcr.io/kodokbakar/pylon/presence-service
    newName: pylon/presence-service
    newTag: latest
  - name: ghcr.io/kodokbakar/pylon/room-service
    newName: pylon/room-service
    newTag: latest
  - name: ghcr.io/kodokbakar/pylon/notification-service
    newName: pylon/notification-service
    newTag: latest

replicas:
  - name: api-gateway
    count: 1
  - name: chat-service
    count: 1
  - name: presence-service
    count: 1
  - name: room-service
    count: 1
  - name: notification-service
    count: 1